#nullable enable
// <auto-generated />
namespace A_Pair.Presentation.Avalonia.Lang;

using System;

[global::System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCode]
[global::System.Runtime.CompilerServices.CompilerGenerated]
public class Resources
{
    private static global::System.Resources.ResourceManager? _resourceMan;

    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (ReferenceEquals(_resourceMan, null))
                _resourceMan = new global::System.Resources.ResourceManager(
                    "A_Pair.Presentation.Avalonia.Lang.Resources", typeof(Resources).Assembly);
            return _resourceMan;
        }
    }

    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture { get; set; } = global::System.Globalization.CultureInfo.CurrentUICulture;

    public static string App_Title => ResourceManager.GetString("App_Title", Culture)!;
    public static string App_AlreadyRunning => ResourceManager.GetString("App_AlreadyRunning", Culture)!;
    public static string App_AlreadyRunningMessage => ResourceManager.GetString("App_AlreadyRunningMessage", Culture)!;
    public static string App_EnvironmentWarning => ResourceManager.GetString("App_EnvironmentWarning", Culture)!;

    public static string Common_OK => ResourceManager.GetString("Common_OK", Culture)!;
    public static string Common_DontRemind => ResourceManager.GetString("Common_DontRemind", Culture)!;
    public static string Common_Later => ResourceManager.GetString("Common_Later", Culture)!;
    public static string Common_Cancel => ResourceManager.GetString("Common_Cancel", Culture)!;
    public static string Lang_System => ResourceManager.GetString("Lang_System", Culture)!;
    public static string Lang_zhCN => ResourceManager.GetString("Lang_zhCN", Culture)!;
    public static string Lang_enUS => ResourceManager.GetString("Lang_enUS", Culture)!;
    public static string Common_Loading => ResourceManager.GetString("Common_Loading", Culture)!;

    public static string Nav_Home => ResourceManager.GetString("Nav_Home", Culture)!;
    public static string Nav_DataManagement => ResourceManager.GetString("Nav_DataManagement", Culture)!;
    public static string Nav_VenueConfig => ResourceManager.GetString("Nav_VenueConfig", Culture)!;
    public static string Nav_Freeform => ResourceManager.GetString("Nav_Freeform", Culture)!;
    public static string Nav_StrategyConfig => ResourceManager.GetString("Nav_StrategyConfig", Culture)!;
    public static string Nav_Seating => ResourceManager.GetString("Nav_Seating", Culture)!;
    public static string Nav_SnapshotHistory => ResourceManager.GetString("Nav_SnapshotHistory", Culture)!;
    public static string Nav_PluginManagement => ResourceManager.GetString("Nav_PluginManagement", Culture)!;
    public static string Nav_Settings => ResourceManager.GetString("Nav_Settings", Culture)!;
    public static string Nav_About => ResourceManager.GetString("Nav_About", Culture)!;
    public static string Nav_CollapseSidebar => ResourceManager.GetString("Nav_CollapseSidebar", Culture)!;
    public static string Nav_ExpandSidebar => ResourceManager.GetString("Nav_ExpandSidebar", Culture)!;

    public static string Settings_Title => ResourceManager.GetString("Settings_Title", Culture)!;
    public static string Settings_Appearance => ResourceManager.GetString("Settings_Appearance", Culture)!;
    public static string Settings_ThemeMode => ResourceManager.GetString("Settings_ThemeMode", Culture)!;
    public static string Settings_DefaultZoom => ResourceManager.GetString("Settings_DefaultZoom", Culture)!;
    public static string Settings_Language => ResourceManager.GetString("Settings_Language", Culture)!;
    public static string Settings_LanguageLabel => ResourceManager.GetString("Settings_LanguageLabel", Culture)!;
    public static string Settings_LanguagePlaceholder => ResourceManager.GetString("Settings_LanguagePlaceholder", Culture)!;
    public static string Settings_LanguageTooltip => ResourceManager.GetString("Settings_LanguageTooltip", Culture)!;
    public static string Settings_Storage => ResourceManager.GetString("Settings_Storage", Culture)!;
    public static string Settings_DataDir => ResourceManager.GetString("Settings_DataDir", Culture)!;
    public static string Settings_DataDirPlaceholder => ResourceManager.GetString("Settings_DataDirPlaceholder", Culture)!;
    public static string Settings_BrowseDataDir => ResourceManager.GetString("Settings_BrowseDataDir", Culture)!;
    public static string Settings_OpenDataDir => ResourceManager.GetString("Settings_OpenDataDir", Culture)!;
    public static string Settings_Behavior => ResourceManager.GetString("Settings_Behavior", Culture)!;
    public static string Settings_ConfirmClear => ResourceManager.GetString("Settings_ConfirmClear", Culture)!;
    public static string Settings_Save => ResourceManager.GetString("Settings_Save", Culture)!;
    public static string Settings_ResetDefaults => ResourceManager.GetString("Settings_ResetDefaults", Culture)!;
    public static string Settings_Saved => ResourceManager.GetString("Settings_Saved", Culture)!;
    public static string Settings_Saving => ResourceManager.GetString("Settings_Saving", Culture)!;
    public static string Settings_SaveFailed => ResourceManager.GetString("Settings_SaveFailed", Culture)!;
    public static string Settings_ResetTitle => ResourceManager.GetString("Settings_ResetTitle", Culture)!;
    public static string Settings_ResetConfirm => ResourceManager.GetString("Settings_ResetConfirm", Culture)!;
    public static string Settings_ResetDone => ResourceManager.GetString("Settings_ResetDone", Culture)!;
    public static string Settings_LoadFailed => ResourceManager.GetString("Settings_LoadFailed", Culture)!;
    public static string Settings_FolderTitle => ResourceManager.GetString("Settings_FolderTitle", Culture)!;
    public static string Settings_FolderFailed => ResourceManager.GetString("Settings_FolderFailed", Culture)!;
    public static string Settings_DirNotFound => ResourceManager.GetString("Settings_DirNotFound", Culture)!;
    public static string Settings_DirNotFoundFormat => ResourceManager.GetString("Settings_DirNotFoundFormat", Culture)!;
    public static string Settings_OpenDirFailed => ResourceManager.GetString("Settings_OpenDirFailed", Culture)!;
    public static string Settings_LangChangedTitle => ResourceManager.GetString("Settings_LangChangedTitle", Culture)!;
    public static string Settings_LangChangedMessage => ResourceManager.GetString("Settings_LangChangedMessage", Culture)!;
    public static string Settings_LangChangedRestart => ResourceManager.GetString("Settings_LangChangedRestart", Culture)!;

    public static string Theme_System => ResourceManager.GetString("Theme_System", Culture)!;
    public static string Theme_Light => ResourceManager.GetString("Theme_Light", Culture)!;
    public static string Theme_Dark => ResourceManager.GetString("Theme_Dark", Culture)!;

    public static string Zoom_75 => ResourceManager.GetString("Zoom_75", Culture)!;
    public static string Zoom_100 => ResourceManager.GetString("Zoom_100", Culture)!;
    public static string Zoom_125 => ResourceManager.GetString("Zoom_125", Culture)!;
    public static string Zoom_150 => ResourceManager.GetString("Zoom_150", Culture)!;

    public static string About_Title => ResourceManager.GetString("About_Title", Culture)!;
    public static string About_Version => ResourceManager.GetString("About_Version", Culture)!;
    public static string About_Runtime => ResourceManager.GetString("About_Runtime", Culture)!;
    public static string About_Framework => ResourceManager.GetString("About_Framework", Culture)!;
    public static string About_License => ResourceManager.GetString("About_License", Culture)!;
    public static string About_Dependencies => ResourceManager.GetString("About_Dependencies", Culture)!;
    public static string About_OpenLink => ResourceManager.GetString("About_OpenLink", Culture)!;
}
