#!/usr/bin/env python3
"""
i18n 管理脚本单元测试。

在 /tmp 隔离环境中运行，不触碰真实 Lang/ 目录。
"""

import os
import re
import shutil
import sys
import tempfile
import unittest
from pathlib import Path

# 将 scripts/ 目录加入 sys.path
SCRIPTS_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SCRIPTS_DIR))

# 导入被测模块
from i18n import (
    ResxFile,
    DesignerFile,
    I18nManager,
    extract_format_args,
    validate_key_name,
    xml_escape,
    DESIGNER_HEADER,
    DESIGNER_PROPERTY_RE,
)


# ──────────────────────────────────────────────
# 测试夹具 — 最小但完整的 .resx 内容
# ──────────────────────────────────────────────

RESX_PREAMBLE = """<?xml version="1.0" encoding="utf-8"?>
<root>
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" />
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3" />
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4" />
              <xsd:attribute ref="xml:space" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>"""


def make_resx_content(entries: list[dict]) -> str:
    """构造完整的 .resx 文件内容。"""
    lines = [RESX_PREAMBLE]
    for e in entries:
        name = e["name"]
        value = xml_escape(e["value"])
        if e.get("comment"):
            comment = xml_escape(e["comment"])
            lines.append(
                f'  <data name="{name}" xml:space="preserve">\n'
                f"    <value>{value}</value>\n"
                f"    <comment>{comment}</comment>\n"
                f"  </data>"
            )
        else:
            lines.append(
                f'  <data name="{name}" xml:space="preserve">\n'
                f"    <value>{value}</value>\n"
                f"  </data>"
            )
    lines.append("</root>\n")
    return "\n".join(lines)


def make_designer_cs_content(keys: list[str], interludes: dict[str, list[str]] = None) -> str:
    """构造 Designer.cs 内容。"""
    lines = [
        "#nullable enable",
        "// <auto-generated />",
        "namespace A_Pair.Presentation.Avalonia.Lang;",
        "",
        "using System;",
        "",
        '[global::System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]',
        "[global::System.Diagnostics.DebuggerNonUserCode]",
        "[global::System.Runtime.CompilerServices.CompilerGenerated]",
        "public class Resources",
        "{",
        "    private static global::System.Resources.ResourceManager? _resourceMan;",
        "",
        '    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]',
        "    public static global::System.Resources.ResourceManager ResourceManager",
        "    {",
        "        get",
        "        {",
        "            if (ReferenceEquals(_resourceMan, null))",
        '                _resourceMan = new global::System.Resources.ResourceManager(',
        '                    "A_Pair.Presentation.Avalonia.Lang.Resources", typeof(Resources).Assembly);',
        "            return _resourceMan;",
        "        }",
        "    }",
        "",
        '    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]',
        "    public static global::System.Globalization.CultureInfo Culture { get; set; } = global::System.Globalization.CultureInfo.CurrentUICulture;",
        "",
    ]
    interludes = interludes or {}
    for key in keys:
        if key in interludes:
            lines.extend(interludes[key])
        lines.append(f'    public static string {key} => ResourceManager.GetString("{key}", Culture)!;')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ──────────────────────────────────────────────
# 测试类
# ──────────────────────────────────────────────

class TestXmlEscape(unittest.TestCase):
    """XML 转义测试。"""

    def test_simple_text(self):
        self.assertEqual(xml_escape("Hello"), "Hello")

    def test_ampersand(self):
        self.assertEqual(xml_escape("a & b"), "a &amp; b")

    def test_angle_brackets(self):
        self.assertEqual(xml_escape("a < b > c"), "a &lt; b &gt; c")

    def test_quotes(self):
        self.assertEqual(xml_escape('a "b"'), "a &quot;b&quot;")

    def test_chinese(self):
        self.assertEqual(xml_escape("中文测试"), "中文测试")

    def test_mixed(self):
        self.assertEqual(xml_escape("确定 & 取消"), "确定 &amp; 取消")


class TestExtractFormatArgs(unittest.TestCase):
    """格式字符串提取测试。"""

    def test_no_args(self):
        self.assertEqual(extract_format_args("Hello"), set())

    def test_single_arg(self):
        self.assertEqual(extract_format_args("Hello {0}"), {0})

    def test_multiple_args(self):
        self.assertEqual(extract_format_args("{0} and {1}"), {0, 1})

    def test_format_specifiers(self):
        self.assertEqual(extract_format_args("{0:F1} {1:N2}"), {0, 1})

    def test_chinese_format(self):
        self.assertEqual(extract_format_args("已添加第 {0} 名学生"), {0})


class TestValidateKeyName(unittest.TestCase):
    """Key 命名校验测试。"""

    def test_valid_keys(self):
        for key in ["Common_OK", "Settings_Title", "Member_MemberCountFmt", "Guide_Phase0_Step0_Title"]:
            with self.subTest(key=key):
                self.assertEqual(validate_key_name(key), [])

    def test_missing_underscore(self):
        issues = validate_key_name("CommonOK")
        self.assertTrue(any("命名规范" in i for i in issues))

    def test_lowercase_start(self):
        issues = validate_key_name("common_OK")
        self.assertTrue(any("命名规范" in i for i in issues))

    def test_double_underscore(self):
        issues = validate_key_name("Common__OK")
        self.assertTrue(any("连续下划线" in i for i in issues))

    def test_unknown_category(self):
        issues = validate_key_name("Foo_BarBaz")
        self.assertTrue(any("已知分类" in i for i in issues))

    def test_too_long(self):
        long_key = "Common_" + "A" * 120
        issues = validate_key_name(long_key)
        self.assertTrue(any("120 字符" in i for i in issues))


class TestResxFile(unittest.TestCase):
    """.resx 文件读写测试。"""

    def setUp(self):
        self.tmpdir = Path(tempfile.mkdtemp(prefix="i18n-test-"))

    def tearDown(self):
        if self.tmpdir.exists():
            shutil.rmtree(self.tmpdir)

    def _write_resx(self, name: str, entries: list[dict]):
        path = self.tmpdir / name
        content = make_resx_content(entries)
        path.write_text(content, encoding="utf-8")
        return path

    def test_load_empty(self):
        path = self._write_resx("empty.resx", [])
        rf = ResxFile(path)
        rf.load()
        self.assertEqual(rf.keys, [])
        self.assertEqual(len(rf.entries), 0)

    def test_load_single_entry(self):
        path = self._write_resx("single.resx", [
            {"name": "Common_OK", "value": "确定", "comment": None},
        ])
        rf = ResxFile(path)
        rf.load()
        self.assertEqual(rf.keys, ["Common_OK"])
        self.assertEqual(rf.get("Common_OK")["value"], "确定")

    def test_load_multiple_entries(self):
        entries = [
            {"name": "Common_Cancel", "value": "取消"},
            {"name": "Common_OK", "value": "确定"},
            {"name": "Common_Save", "value": "保存"},
        ]
        path = self._write_resx("multi.resx", entries)
        rf = ResxFile(path)
        rf.load()
        self.assertEqual(rf.keys, ["Common_Cancel", "Common_OK", "Common_Save"])

    def test_load_with_comment(self):
        entries = [
            {"name": "Seating_Export", "value": "导出", "comment": "导出按钮"},
        ]
        path = self._write_resx("with_comment.resx", entries)
        rf = ResxFile(path)
        rf.load()
        self.assertEqual(rf.get("Seating_Export")["comment"], "导出按钮")

    def test_load_special_characters(self):
        entries = [
            {"name": "Test_Ampersand", "value": "确定 & 取消"},
        ]
        path = self._write_resx("special.resx", entries)
        rf = ResxFile(path)
        rf.load()
        # XML 解析后应该自动还原 &amp; → &
        self.assertEqual(rf.get("Test_Ampersand")["value"], "确定 & 取消")

    def test_round_trip(self):
        """写入 → 重新加载，验证数据完整性。"""
        entries = [
            {"name": "About_Title", "value": "关于"},
            {"name": "Common_Cancel", "value": "取消"},
            {"name": "Common_OK", "value": "确定", "comment": "确认按钮"},
            {"name": "Settings_Title", "value": "设置"},
        ]
        path = self._write_resx("rt.resx", entries)

        rf = ResxFile(path)
        rf.load()
        rf.save()

        rf2 = ResxFile(path)
        rf2.load()

        self.assertEqual(rf2.keys, ["About_Title", "Common_Cancel", "Common_OK", "Settings_Title"])
        self.assertEqual(rf2.get("Common_OK")["value"], "确定")
        self.assertEqual(rf2.get("Common_OK")["comment"], "确认按钮")

    def test_add_maintains_order(self):
        path = self._write_resx("add_order.resx", [
            {"name": "Common_Cancel", "value": "取消"},
            {"name": "Common_OK", "value": "确定"},
        ])
        rf = ResxFile(path)
        rf.load()
        rf.add("Common_Save", "保存")
        rf.save()

        rf2 = ResxFile(path)
        rf2.load()
        self.assertEqual(rf2.keys, ["Common_Cancel", "Common_OK", "Common_Save"])

    def test_add_beginning(self):
        path = self._write_resx("add_beg.resx", [
            {"name": "Common_OK", "value": "确定"},
        ])
        rf = ResxFile(path)
        rf.load()
        rf.add("About_Title", "关于")
        rf.save()

        rf2 = ResxFile(path)
        rf2.load()
        self.assertEqual(rf2.keys, ["About_Title", "Common_OK"])

    def test_modify_value(self):
        path = self._write_resx("mod.resx", [
            {"name": "Common_OK", "value": "确定"},
        ])
        rf = ResxFile(path)
        rf.load()
        rf.modify("Common_OK", value="好的")
        self.assertEqual(rf.get("Common_OK")["value"], "好的")

    def test_modify_comment(self):
        path = self._write_resx("mod_comment.resx", [
            {"name": "Common_OK", "value": "确定"},
        ])
        rf = ResxFile(path)
        rf.load()
        rf.modify("Common_OK", comment="新的注释")
        self.assertEqual(rf.get("Common_OK")["comment"], "新的注释")

    def test_modify_clear_comment(self):
        path = self._write_resx("mod_clear.resx", [
            {"name": "Common_OK", "value": "确定", "comment": "旧注释"},
        ])
        rf = ResxFile(path)
        rf.load()
        rf.modify("Common_OK", clear_comment=True)
        self.assertIsNone(rf.get("Common_OK")["comment"])

    def test_rename(self):
        path = self._write_resx("rename.resx", [
            {"name": "Common_OK", "value": "确定"},
            {"name": "Common_Save", "value": "保存"},
        ])
        rf = ResxFile(path)
        rf.load()
        rf.rename("Common_OK", "Common_Confirm")
        rf.save()

        rf2 = ResxFile(path)
        rf2.load()
        self.assertNotIn("Common_OK", rf2.name_index)
        self.assertEqual(rf2.get("Common_Confirm")["value"], "确定")
        self.assertEqual(rf2.keys, ["Common_Confirm", "Common_Save"])

    def test_delete(self):
        path = self._write_resx("delete.resx", [
            {"name": "Common_OK", "value": "确定"},
            {"name": "Common_Save", "value": "保存"},
        ])
        rf = ResxFile(path)
        rf.load()
        rf.delete("Common_OK")
        self.assertEqual(rf.keys, ["Common_Save"])
        self.assertNotIn("Common_OK", rf.name_index)

    def test_duplicate_key_detected(self):
        """重复 key 应抛出 ValueError。"""
        path = self._write_resx("dup.resx", [
            {"name": "Common_OK", "value": "确定"},
        ])
        # 手动修改文件插入重复 key
        content = path.read_text(encoding="utf-8")
        # 在现有 data 元素后复制一份
        content = content.replace(
            '</data>\n</root>',
            '</data>\n  <data name="Common_OK" xml:space="preserve">\n    <value>确定2</value>\n  </data>\n</root>',
        )
        path.write_text(content, encoding="utf-8")
        rf = ResxFile(path)
        with self.assertRaises(ValueError):
            rf.load()


class TestDesignerFile(unittest.TestCase):
    """Designer.cs 解析/生成测试。"""

    def setUp(self):
        self.tmpdir = Path(tempfile.mkdtemp(prefix="i18n-test-"))

    def tearDown(self):
        if self.tmpdir.exists():
            shutil.rmtree(self.tmpdir)

    def _write_designer(self, keys: list[str], interludes: dict[str, list[str]] = None):
        path = self.tmpdir / "Resources.Designer.cs"
        content = make_designer_cs_content(keys, interludes)
        path.write_text(content, encoding="utf-8")
        return path

    def test_load_simple(self):
        path = self._write_designer(["Common_OK", "Common_Save"])
        df = DesignerFile(path)
        df.load()
        self.assertEqual(set(df.properties.keys()), {"Common_OK", "Common_Save"})
        self.assertEqual(df.properties["Common_OK"], "Common_OK")

    def test_load_with_interludes(self):
        interludes = {
            "Guide_Welcome_Greeting_Title": [
                "\n",
                "    // ===== 新版引导资源键 =====\n",
            ],
        }
        path = self._write_designer(
            ["Common_Save", "Guide_Welcome_Greeting_Title"],
            interludes,
        )
        df = DesignerFile(path)
        df.load()
        self.assertIn("Guide_Welcome_Greeting_Title", df.interstitial)
        self.assertIn("// ===== 新版引导资源键 =====", "".join(df.interstitial["Guide_Welcome_Greeting_Title"]))

    def test_generate_from_scratch(self):
        """使用 header 模板生成。"""
        path = self._write_designer([])
        # 写入空文件
        path.write_text("", encoding="utf-8")
        df = DesignerFile(path)
        df.load()  # 空文件，header_lines 和 properties 都为空

        content = df.generate(["Common_OK", "Common_Save"])
        self.assertIn("public static string Common_OK", content)
        self.assertIn("public static string Common_Save", content)
        self.assertIn("ResourceManager.GetString", content)

    def test_generate_preserves_interludes(self):
        interludes = {
            "Guide_New_Title": ["\n", "    // 分隔注释\n"],
        }
        path = self._write_designer(
            ["Common_OK", "Guide_New_Title"],
            interludes,
        )
        df = DesignerFile(path)
        df.load()

        content = df.generate(["Common_OK", "Guide_New_Title"])
        self.assertIn("// 分隔注释", content)

    def test_generate_missing_interlude_key(self):
        """interstitial key 不在 key 列表中时不应崩溃。"""
        interludes = {
            "Old_Orphan_Key": ["    // 旧注释\n"],
        }
        path = self._write_designer(
            ["Common_OK"],
            interludes,
        )
        df = DesignerFile(path)
        df.load()

        # Old_Orphan_Key 不在新 key 列表中，generate 应正常处理
        content = df.generate(["Common_OK"])
        self.assertIn("Common_OK", content)


class TestI18nManager(unittest.TestCase):
    """I18nManager 集成测试。"""

    def setUp(self):
        self.tmpdir = Path(tempfile.mkdtemp(prefix="i18n-test-"))
        self.lang_dir = self.tmpdir / "Lang"
        self.lang_dir.mkdir(parents=True)

        # 创建最小三文件
        zh_path = self.lang_dir / "Resources.resx"
        en_path = self.lang_dir / "Resources.en-US.resx"
        designer_path = self.lang_dir / "Resources.Designer.cs"

        zh_path.write_text(make_resx_content([
            {"name": "Common_OK", "value": "确定"},
            {"name": "Common_Save", "value": "保存"},
            {"name": "Settings_Title", "value": "设置"},
        ]), encoding="utf-8")

        en_path.write_text(make_resx_content([
            {"name": "Common_OK", "value": "OK"},
            {"name": "Common_Save", "value": "Save"},
            {"name": "Settings_Title", "value": "Settings"},
        ]), encoding="utf-8")

        designer_path.write_text(make_designer_cs_content(
            ["Common_OK", "Common_Save", "Settings_Title"],
        ), encoding="utf-8")

        self.mgr = I18nManager(self.lang_dir)

    def tearDown(self):
        if self.tmpdir.exists():
            shutil.rmtree(self.tmpdir)

    def test_load_all(self):
        self.mgr.load_all()
        self.assertEqual(len(self.mgr.resx_zh.entries), 3)
        self.assertEqual(len(self.mgr.resx_en.entries), 3)
        self.assertEqual(len(self.mgr.designer.properties), 3)

    def test_check_passes(self):
        self.mgr.load_all()
        issues = self.mgr.check()
        self.assertEqual(issues, [])

    def test_check_detects_missing_en_key(self):
        self.mgr.load_all()
        self.mgr.resx_en.delete("Common_OK")
        self.mgr.resx_en.save()

        self.mgr.load_all()
        issues = self.mgr.check()
        errors = [i for i in issues if i["level"] == "ERROR"]
        self.assertTrue(any("Common_OK" in e["msg"] and "en-US" in e["msg"] for e in errors))

    def test_check_detects_format_arg_mismatch(self):
        self.mgr.load_all()
        self.mgr.resx_zh.modify("Common_OK", value="确定 {0}")
        self.mgr.resx_zh.save()
        self.mgr.resx_en.save()  # en still "OK" without {0}

        self.mgr.load_all()
        issues = self.mgr.check()
        errors = [i for i in issues if i["level"] == "ERROR" and "格式字符串" in i["msg"]]
        self.assertTrue(len(errors) > 0)

    def test_check_detects_missing_designer_key(self):
        """key 在 .resx 但不在 Designer.cs。"""
        # 在 zh .resx 中添加 key 但不更新 designer
        self.mgr.load_all()
        self.mgr.resx_zh.add("Common_New", "新")
        self.mgr.resx_en.add("Common_New", "New")
        self.mgr.resx_zh.save()
        self.mgr.resx_en.save()

        self.mgr.load_all()
        issues = self.mgr.check()
        errors = [i for i in issues if i["level"] == "ERROR" and "Common_New" in i["msg"]]
        self.assertTrue(len(errors) > 0)

    def test_backup_creates_files(self):
        self.mgr.load_all()
        self.mgr.backup()

        backups = list(self.lang_dir.glob(".backup/*"))
        self.assertEqual(len(backups), 3)  # zh, en, designer

    def test_save_all_regenerates_designer(self):
        self.mgr.load_all()
        self.mgr.resx_zh.add("Common_New", "新")
        self.mgr.resx_en.add("Common_New", "New")
        self.mgr.save_all()

        # 验证 designer 已更新
        with open(self.lang_dir / "Resources.Designer.cs", "r", encoding="utf-8") as f:
            content = f.read()
        self.assertIn("Common_New", content)

    def test_add_workflow(self):
        """模拟 add 命令的完整流程。"""
        self.mgr.load_all()
        self.mgr.backup()
        self.mgr.resx_zh.add("Common_Refresh", "刷新")
        self.mgr.resx_en.add("Common_Refresh", "Refresh")
        self.mgr.save_all()

        # 验证三文件一致性
        self.mgr.load_all()
        issues = self.mgr.check()
        self.assertEqual(issues, [])

        zh_val = self.mgr.resx_zh.get("Common_Refresh")["value"]
        en_val = self.mgr.resx_en.get("Common_Refresh")["value"]
        self.assertEqual(zh_val, "刷新")
        self.assertEqual(en_val, "Refresh")

    def test_delete_workflow(self):
        self.mgr.load_all()
        self.mgr.backup()
        self.mgr.resx_zh.delete("Common_Save")
        self.mgr.resx_en.delete("Common_Save")
        self.mgr.save_all()

        self.mgr.load_all()
        self.assertNotIn("Common_Save", self.mgr.resx_zh.name_index)
        self.assertNotIn("Common_Save", self.mgr.resx_en.name_index)
        self.assertNotIn("Common_Save", self.mgr.designer.properties)


if __name__ == "__main__":
    unittest.main(verbosity=2)
